# config.yaml

experiment:
  name: "cell_vae_experiment"
  neptune_project: "benyla/Bachelor"

training:
  epochs: 30
  batch_size: 16
  learning_rate: 0.001

model:
  in_channels: 3
  latent_dim: 20

data:
  dummy: False
  folder_path: "data/sample_cell_data"