# config.yaml

experiment:
  name: "dummy_vae_experiment"
  neptune_project: "benyla/Bachelor"

training:
  epochs: 10
  batch_size: 32
  learning_rate: 0.001

model:
  in_channels: 1
  latent_dim: 20  
  image_size: 64

data:
  dummy: true 
