# config.yaml

experiment:
  name: "dummy_vae_experiment"
  neptune_project: "your_workspace/your_project"
  neptune_api_token: "YOUR_API_TOKEN"  # Consider using environment variables for secrets

training:
  epochs: 10
  batch_size: 32
  learning_rate: 0.001

model:
  in_channels: 3
  latent_dim: 128
  image_size: 64

data:
  dummy: true  # A flag to indicate using dummy data
