# config.yaml

metadata_csv: /zhome/70/5/14854/nobackup/deeplearningf22/bbbc021/singlecell/metadata.csv

experiment:
  name: "VAE+overfit"
  neptune_project: "benyla/Bachelor"
  tags: "cell_vae -- full_data"

training:
  epochs: 500
  batch_size: 8
  lr_VAE: 0.001
  lr_D: 0.001

model:
  in_channels: 3
  latent_dim: 64
  use_adv: True
  beta: 0
  T: 2500
  overfit: True 

data:
  test: True