metadata_csv: /zhome/70/5/14854/nobackup/deeplearningf22/bbbc021/singlecell/metadata.csv

experiment:
  name: "VAE_128"
  neptune_project: "benyla/Bachelor"
  tags: "VAE_128"

training:
  epochs: 50
  batch_size: 256
  lr_VAE: 0.001

model:
  in_channels: 3
  latent_dim: 128
  overfit: False

data:
  test: False